import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={'/'}><a>Home</a></Link>
      <Link href={'/about'}><a> About</a></Link>
      <Link href={'/blog'}><a> Blog</a></Link>
 
    </div>
  )
}
